
project: exp
entity: rlpractitioner

main:
  env: Vrep
  vrep: true
  log: true
  visit: false
  render: false
  save_model: false
  load_model: false
  start_timesteps: 1000
  max_timesteps: 1000000
  offpolicy: false
  flat_agent: true 
  batch_size: 128
  model: TD3
  eval_freq: 50000
  
  c_step: 10
  decay: false 
  step_decayer:
    total_steps: 700000
    init_step: ${main.c_step}
    min_step: 5

