
coppeliagym:
  sim:
    scene_file: 'coppelia_scenes/kuka.ttt'
    render_scene_file: 'coppelia_scenes/kuka_render.ttt'
    headless: true
    sim_timestep: 0.03
    render: ${main.render}

  params:
    # Output of gripper.actuate() and gripper.get_amount() need to be scaled to 0 - 1
    gripper_range: [0.33, 0.55]
    sub_mock: ${agent.sub_mock}
    render: ${main.render}
    # Taken from Kuka14 Tech Sheet
    max_torque: [320, 320, 176, 176, 110, 40, 40] 
    max_vel: [85, 85, 100, 75, 130, 135, 135] # In deg/s. In the sim, they convert to rad/s
    ee_pos: false
    ee_j_pos: true
    force: false 
    random_target: true 
    random_eval_target: true
    sparse_rew: false
    action_regularizer: 0.00000
    distance_function: euclid
    spherical_coord: ${agent.spherical_coord}
    flat_agent: ${main.flat_agent}
    reversal_time: 100000000
    touch_distance: 0.08
    minimum_dist: 0.
    record_touches: false
    reset_on_wrong_sequence: false
    punishment: 0
    task: 'dense'
    state_max: [1.5, 0.34, 1.83, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14,1.93,1.92,1.64,2.05,2.15,2.4,2.4,2.7,2.9,2.85,1.44,0.2,1,1.43,0.16,1]
    state_min: [-0.3,-1.6,0.52, -3.14, -3.14, -3.14, -3.14, -3.14, -3.14, -3.14, -2.05,-2.35,-2.22,-1.84,-2.18,-2.74,-2.09,-2.68,-4.71,2.76,-0.21,-1.48,0,-0.2,-1.4,0]
    normalize: false

  subgoals:
    ee_goal: 5.
    j_goal: 3.14
    ej_goal: [3, 1.] # Subgoal length and range [L,R]

