
project: expo
entity: rlpractitioner

main:
  env: Vrep
  vrep: true
  log: true
  minilog: false
  visit: false
  render: false
  save_model: false
  load_model: false
  load_string: 'None'
  start_timesteps: 5000
  max_timesteps: 1500000
  time_limit: ${coppeliagym.params.time_limit}
  offpolicy: false
  flat_agent: false 
  batch_size: 128
  model: TD3
  eval_freq: 20000
  seed: 15
  train_every: 300 
  gradient_steps: 300 
  no_seed: false
  simple_env: false

  
  c_step: 40
  decay: false 
  step_decayer:
    total_steps: 700000
    init_step: ${main.c_step}
    min_step: 5

