
coppeliagym:
  sim:
    scene_file: 'coppelia_scenes/kuka.ttt'
    render_scene_file: 'coppelia_scenes/kuka_render.ttt'
    headless: true
    sim_timestep: 0.03
    render: ${main.render}

  params:
    # Output of gripper.actuate() and gripper.get_amount() need to be scaled to 0 - 1
    gripper_range: [0.33, 0.55]
    sub_mock: ${agent.sub_mock}
    render: ${main.render}
    # Taken from Kuka14 Tech Sheet
    max_vel: [320, 320, 176, 176, 110, 40, 40] # In deg/s. In the sim, they convert to rad/s
    max_torque: [85, 85, 100, 75, 130, 135, 135]
    ee_pos: false
    ee_j_pos: true
    force: false 
    random_target: true 
    random_eval_target: true
    sparse_rew: false
    action_regularizer: 0.00000
    distance_function: euclid
    spherical_coord: ${agent.spherical_coord}
    flat_agent: ${main.flat_agent}
    reversal_time: 100000000
    touch_distance: 0.08
    minimum_dist: 0.
    record_touches: false
    reset_on_wrong_sequence: false
    punishment: 0
    reward_type: 'dense'

  subgoals:
    ee_goal: 5.
    j_goal: 3.14
    ej_goal: [3, 1.] # Subgoal length and range [L,R]

