
buffer:
  c_step: ${main.c_step}
  offpolicy: ${main.offpolicy}
  max_size: 227000

agent:
  # Params for the Agent. In case of flat agent, the sub-agent params
  # will be used.
  spherical_coord: false 
  center_meta_goal: true
  sub_mock: false
  meta_mock: false
  goal_type: Absolute
  ri_re: false
  zero_obs: 0
  num_eval_episodes: 10
  sub_rew_scale: 1
  meta_rew_scale: 0.1
  sub_noise: 1.4
  meta_noise: 0.1
  train_meta: true
  train_sub: true
  seed: ${main.seed}
  c_step: ${main.c_step}

  meta_model:
    ac_hidden_layers: [300, 300]
    cr_hidden_layers: [300, 300]
    clip_cr: 10000.5
    clip_ac: 10000.5
    reg_coeff_ac: 0.0
    reg_coeff_cr: 0.0
    name: 'meta'
    discount: 0.99
    tau: 0.005
    policy_noise: 0.2
    noise_clip: 0.5
    policy_freq: 2
    ac_lr: 0.000963
    cr_lr: 0.000728
    offpolicy: ${main.offpolicy}
    c_step: ${main.c_step}
    no_candidates: 10

  sub_model:
    ac_hidden_layers: [300, 300]
    cr_hidden_layers: [300, 300]
    clip_cr: 5.0
    clip_ac: 5.0
    reg_coeff_ac: 0.000009
    reg_coeff_cr: 0.00003
    name: 'sub'
    discount: 0.977
    tau: 0.00533
    policy_noise: 0.1705
    noise_clip: 0.63
    policy_freq: 4
    ac_lr: 0.00043
    cr_lr: 0.00075
    offpolicy: ${main.offpolicy}
    c_step: ${main.c_step}
    no_candidates: 10

