env: Vrep
vrep: true
c_step: 10
subgoal_ee_range: 5.0
ri_re: false 
sparse_rew: false 
offpolicy: true 
flat_agent: true


ee_pos: true
ee_j_pos: false 



decay: false
step_decayer:
  total_steps: 200000
  init_step: ${c_step}
  min_step: 5

