env: Vrep
vrep: true
ee_j_pos: true 
ee_pos: false 
c_step: 10
subgoal_ee_range: 5.0
ri_re: false 
sparse_rew: false 
offpolicy: true 

decay: false
step_decayer:
  total_steps: 200000
  init_step: ${c_step}
  min_step: 5

