env: Vrep
vrep: true

offpolicy: false 
flat_agent: false 

sparse_rew: false 
ri_re: true 

subgoal_ee_range: 5.0
ee_pos: false 
ee_j_pos: true 



c_step: 100
decay: true 
step_decayer:
  total_steps: 700000
  init_step: ${c_step}
  min_step: 5

