project: exp
env: Vrep
vrep: true
eval_freq: 1000
start_timesteps: 0
# Action Space---------------------
force: false

# State params ---------------------
ee_pos: false 
ee_j_pos: true 


flat_agent: true 

# Meta params --------------------
offpolicy: false 
sparse_rew: false 
ri_re: false
subgoal_ee_range: 5.0


c_step: 10
decay: false 
step_decayer:
  total_steps: 700000
  init_step: ${c_step}
  min_step: 5

